function IdeaMenus() { }

IdeaMenus.fileMenu = { id:"file", name:"File", entries:[
        { id:"NewProject", name:"New Project...", icon:"smiley" },
        { id: "NewModule", name:"New Module..." },
        { name:"Open Project..." },
        { name:"Open File..." },
        { name:"Reopen", entries:[
                { name:"Me" },
                { name:"Myself" },
                { name:"Irene" },
                { name:"Another Person" }] },
        { name:"Close Project" },
        ButtonBarIt.separator,
        { name:"Settings" },
        { name:"Template Project Settings" },
        ButtonBarIt.separator,
        { name:"Save All" },
        { name:"Export Settings..." },
        { name:"Import Settings..." },
        ButtonBarIt.separator,
        { name:"Import from JBuilder" },
        ButtonBarIt.separator,
        { name:"Synchronize" },
        { name:"Reload from Disk" },
        ButtonBarIt.separator,
        { name:"Checkout from Version Control", entries: [
                { name:"SVN" },
                { name:"CVS" }] },
        ButtonBarIt.separator,
        { name:"Browse SVN Repository..." },
        ButtonBarIt.separator,
        { name:"Import into CVS..." },
        { name:"Browse CVS Repository..." },
        ButtonBarIt.separator,
        { name:"Export to HTML..." },
        { name:"Print..." },
        ButtonBarIt.separator,
        { name:"Quit" }] };

IdeaMenus.editMenu = { id:"edit", name:"Edit", entries:[
        { name:"Undo" },
        { name:"Redo" },
        ButtonBarIt.separator,
        { name:"Cut" },
        { name:"Copy" },
        { name:"Copy Path" },
        { name:"Copy Reference" },
        { name:"Paste" },
        { name:"Paste..." },
        { name:"Paste Simple" },
        { name:"Column Mode" },
        ButtonBarIt.separator,
        { name:"Select All" },
        ButtonBarIt.separator,
        { name:"New..." },
        { name:"Delete" },
        { name:"Toggle Bookmark" },
        { name:"Show Bookmarks" }] };

IdeaMenus.searchMenu = { id:"search", name:"Search", entries:[
        { name:"Find..." },
        { name:"Replace..." },
        { name:"Find Next" },
        { name:"Find Previous" },
        { name:"Find Word at Caret" },
        { name:"Incremental Search", entries:IdeaMenus.fileMenu.entries },
        ButtonBarIt.separator,
        { name:"Find Usages..." },
        { name:"Find Usages in File..." },
        { name:"Highlight Usages in File" },
        ButtonBarIt.separator,
        { name:"Find in Path..." },
        { name:"Replace in Path..." },
        { name:"Search Structurally..." },
        { name:"Replace Structurally..." }] };

IdeaMenus.viewMenu = { id:"view", name:"View", entries:[
        { name:"Toolbar" },
        { name:"Status Bar" },
        { name:"Show Whitespace" },
        { name:"Show Line Numbers" },
        ButtonBarIt.separator,
        { name:"Full Screen" },
        ButtonBarIt.separator,
        { name:"File Structure Popup" },
        { name:"Select In..." },
        { name:"Quick Documentation Lookup" },
        { name:"Quick Definition Lookup" },
        { name:"Parameter Info" },
        { name:"Context Info" },
        { name:"Error Description" },
        ButtonBarIt.separator,
        { name:"Add To Favorites", entries:[] },
        ButtonBarIt.separator,
        { name:"Jump to Source" },
        { name:"Show Source" },
        { name:"Open in Browser" },
        ButtonBarIt.separator,
        { name:"External JavaDoc" },
        { name:"Recent Files..." },
        { name:"Quick Switch Scheme..." },
        ButtonBarIt.separator,
        { name:"Method Hierarchy" },
        { name:"Call Hierarchy" },
        ButtonBarIt.separator,
        { name:"Folding", entries:[] },
        ButtonBarIt.separator,
        { name:"Recent Changes..." }] };

IdeaMenus.gotoMenu = { id:"goto", name:"Go To", entries:[
         { name:"Class..." },
         { name:"File..." },
         { name:"Symbol..." },
         { name:"Line..." },
         ButtonBarIt.separator,
         { name:"Declaration" },
         { name:"Implementation" },
         { name:"Type Declaration" },
         { name:"Super Method" },
         ButtonBarIt.separator,
         { name:"Next Highlighted Error" },
         { name:"Previous Highlighted Error" },
         ButtonBarIt.separator,
         { name:"Next Method" },
         { name:"Previous Method" },
         ButtonBarIt.separator,
         { name:"Next Bookmark" },
         { name:"Previous Bookmark" },
         ButtonBarIt.separator,
         { name:"Back" },
         { name:"Forward" },
         { name:"Last Edit Location" },
         ButtonBarIt.separator,
         { name:"Go To Next Change" },
         { name:"Go To Prev Change" }] };

IdeaMenus.codeMenu = { id:"code", name:"Code", entries:[
         { name:"Override Methods..." },
         { name:"Implement Methods..." },
         { name:"Delegate Methods..." },
         ButtonBarIt.separator,
         { name:"Surround With..." },
         { name:"Generate..." },
         ButtonBarIt.separator,
         { name:"Complete Code", entries:[] },
         ButtonBarIt.separator,
         { name:"Insert Live Template..." },
         { name:"Surround with Live Template..." },
        ButtonBarIt.separator,
         { name:"Comment with Line Comment" },
         { name:"Comment with Block Comment" },
         { name:"Reformat Code..." },
         { name:"Auto-Indent Lines" },
         { name:"Optimize Imports..." },
         ButtonBarIt.separator,
         { name:"Move Statement Down" },
         { name:"Move Statement Up" }] };

IdeaMenus.analyzeMenu = { id:"analyze", name:"Analyze", entries:[
         { name:"Inspect Code..." },
         { name:"Inspect Code With Editor Settings" },
         { name:"View Offline Inspection Results..." },
         ButtonBarIt.separator,
         { name:"Analyze Dependencies..." },
         { name:"Analyze Backward Dependencies..." },
         { name:"Analyze Cyclic Dependencies..." },
         { name:"Analyze Module Dependencies..." },
         { name:"Locate Duplicates..." },
         ButtonBarIt.separator,
         { name:"Analyze Stacktrace..." }] };

IdeaMenus.refactorMenu = { id:"refactor", name:"Refactor", entries:[
         { name:"Rename..." },
         { name:"Change Signature..." },
         { name:"Make Static..." },
         { name:"Convert To Instance Method..." },
         ButtonBarIt.separator,
         { name:"Move..." },
         { name:"Copy..." },
         { name:"Safe Delete..." },
         ButtonBarIt.separator,
         { name:"Extract Method..." },
         { name:"Replace Method Code Duplicates..." },
         { name:"Introduce Variable..." },
         { name:"Introduce Field..." },
         { name:"Introduce Constant..." },
         { name:"Introduce Parameter..." },
         ButtonBarIt.separator,
         { name:"Extract Interface..." },
         { name:"Extract Superclass..." },
         { name:"Use Interface Where Possible..." },
         { name:"Pull Members Up..." },
         { name:"Push Members Down..." },
         { name:"Replace Inheritance with Delegation..." },
         ButtonBarIt.separator,
         { name:"Inline..." },
         { name:"Convert Anonymous to Inner..." },
         { name:"Encapsulate Fields..." },
         { name:"Replace Temp with Query..." },
         { name:"Replace Constructor with Factory Method..." },
         ButtonBarIt.separator,
         { name:"Generify..." },
         { name:"Migrate..." },
         ButtonBarIt.separator,
         { name:"Extract Include File..." }] };

IdeaMenus.buildMenu = { id:"build", name:"Build", entries:[
         { name:"Rebuild Project" },
         { name:"Make Project" },
         { name:"Make Module" },
         { name:"Compile" },
         ButtonBarIt.separator,
         { name:"Generate Ant Build" },
         ButtonBarIt.separator,
         { name:"Build Jars..." }] };

IdeaMenus.helpMenu = { id:"help", name:"Help" };